name: Trigger website deployment

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ikalogic-website-v2 deploy workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WEBSITE_TOKEN }}" \
            https://api.github.com/repos/ikalogic/ikalogic-website-v2/dispatches \
            -d '{"event_type":"trigger-website-deploy","client_payload":{"source_repo":"ScanaStudio-scripts-v3","branch":"master"}}'
